"""добавил category_id в activities

Revision ID: 7003056a55bd
Revises: 81bc1f16c9f3
Create Date: 2026-08-20 07:14:23.141336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7003056a55bd'
down_revision: Union[str, Sequence[str], None] = '81bc1f16c9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'category_id')
    # ### end Alembic commands ###
