"""добавил device flow: device_codes, refresh_token_hash

Revision ID: 004b54f4aeb8
Revises: 4fcd6c8043c9
Create Date: 2026-08-29 14:38:47.900804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004b54f4aeb8'
down_revision: Union[str, Sequence[str], None] = '4fcd6c8043c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_device_codes_code', 'device_codes', ['code'], unique=False)
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    op.drop_index('ix_device_codes_code', table_name='device_codes')
    op.drop_table('device_codes')
    # ### end Alembic commands ###
