"""добавил user_id в activities

Revision ID: 6e4db7cdbdda
Revises: acb72103f31e
Create Date: 2026-08-29 07:31:02.073149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4db7cdbdda'
down_revision: Union[str, Sequence[str], None] = 'acb72103f31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('ix_activities_started_at', 'activities', ['started_at'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_started_at', table_name='activities')
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
