"""добавил telegram_id, username/hashed_password стали опциональными

Revision ID: b2a9d4445990
Revises: 6e4db7cdbdda
Create Date: 2026-08-29 08:20:23.691257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a9d4445990'
down_revision: Union[str, Sequence[str], None] = '6e4db7cdbdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
